import React from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Shield } from 'lucide-react'

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background text-ink py-16 px-4 sm:px-6 lg:px-8 grid-bg">
      <div className="max-w-3xl mx-auto glass p-8 sm:p-12 rounded-3xl border border-divider shadow-xl relative z-10">
        <Link to="/" className="inline-flex items-center gap-2 text-primary hover:text-primary-dark transition-colors mb-8 font-semibold">
          <ArrowLeft size={18} />
          Back to home
        </Link>
        
        <div className="flex items-center gap-4 mb-6">
          <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary">
            <Shield size={24} />
          </div>
          <h1 className="text-3xl font-extrabold font-display">Privacy Policy</h1>
        </div>
        <p className="text-muted mb-8 font-mono text-sm">Last updated: August 14, 2026</p>

        <div className="space-y-6 text-muted leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-ink mb-3 font-display">1. Introduction</h2>
            <p>
              At ggit.ai, we take your privacy and data security with absolute clinical seriousness. This Privacy Policy describes how we collect, use, and process your personal information, as well as the data generated by patients communicating with our AI Voice Assistants.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3 font-display">2. Compliance Standards</h2>
            <p>
              Our data processing architectures are designed from the ground up to comply fully with:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>US Health Insurance Portability and Accountability Act (HIPAA)</li>
              <li>Swiss Federal Act on Data Protection (FADP)</li>
              <li>UK Data Protection Act & EU General Data Protection Regulation (GDPR)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3 font-display">3. Data We Process</h2>
            <p>
              We process information related to dental practices (such as email, name, clinic PMS calendar slots) and voice-to-text transcripts of patient bookings. Patient-releasing medical logs and audio snippets are heavily encrypted and strictly protected against unauthorized access.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-ink mb-3 font-display">4. Contact Us</h2>
            <p>
              If you have any questions or concerns about your data, please contact our systems security engineers at <span className="text-ink font-semibold">security@ggit.ai</span>.
            </p>
          </section>
        </div>
      </div>
      <div className="noise-overlay"></div>
    </div>
  )
}
